apiVersion: v1
kind: Pod
metadata:
  name: nginx-single-pod
  labels:
    apps: nginx
    namespace: learn
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
      - containerPort: 80
      - containerPort: 443
