apiVersion: v1
kind: Pod
metadata:
  name: nginx-namespace-pod
  namespace: learn
  labels:
    apps: nginx-ns
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
      - containerPort: 80
      - containerPort: 443
